# Generated by Django 6.0.7 on 2026-07-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the password was last changed. Tokens issued before this timestamp are rejected.', null=True),
        ),
    ]
