# Generated by Django 6.0.7 on 2026-07-31 11:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address associated with the authentication event. Captured for failed login attempts where no user can be resolved.', max_length=254),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token_jti', models.CharField(db_index=True, help_text='JWT Refresh Token JTI', max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, help_text='Desktop, Mobile, Tablet, API, etc.', max_length=100)),
                ('browser', models.CharField(blank=True, max_length=150)),
                ('operating_system', models.CharField(blank=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('login_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'db_table': 'authentication_user_session',
                'ordering': ('-last_activity_at',),
                'indexes': [models.Index(fields=['company', 'user'], name='authenticat_company_7ad2e3_idx'), models.Index(fields=['company', 'is_active'], name='authenticat_company_372123_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_a98d8c_idx'), models.Index(fields=['last_activity_at'], name='authenticat_last_ac_38d2e5_idx'), models.Index(fields=['refresh_token_jti'], name='authenticat_refresh_eb5f71_idx')],
            },
        ),
    ]
