# Generated by Django 4.2.30 on 2026-08-03 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_loginhistory_email_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOtp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Normalized email the OTP was issued to.', max_length=254)),
                ('otp_hash', models.CharField(help_text='SHA-256 hash of the 6-digit OTP.', max_length=64)),
                ('expires_at', models.DateTimeField(help_text='OTP is no longer valid after this timestamp.')),
                ('is_used', models.BooleanField(default=False, help_text='Marked True once the OTP has been successfully verified.')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of failed verification attempts against this OTP.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset OTP',
                'verbose_name_plural': 'Password Reset OTPs',
                'db_table': 'authentication_password_reset_otp',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['email', 'is_used'], name='authenticat_email_ffd674_idx'), models.Index(fields=['email', 'expires_at'], name='authenticat_email_f8ba19_idx')],
            },
        ),
    ]
