# Generated by Django 6.0.7 on 2026-07-29 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('system', 'System Architecture'), ('data', 'Data Architecture'), ('network', 'Network Architecture'), ('cloud', 'Cloud Architecture'), ('integration', 'Integration Architecture'), ('security', 'Security Architecture')], default='system', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='architecture/')),
                ('diagram_url', models.URLField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='architecture_diagrams_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architecture_diagrams', to='projects.project')),
            ],
            options={
                'db_table': 'architecture_diagrams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('ai_ml', 'AI/ML'), ('infrastructure', 'Infrastructure'), ('other', 'Other')], default='other', max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('license_type', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_stacks', to='projects.project')),
            ],
            options={
                'db_table': 'technology_stacks',
                'ordering': ['category', 'name'],
            },
        ),
    ]
