# Generated by Django 6.0.7 on 2026-07-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="scope",
            field=models.CharField(
                choices=[("tenant", "Tenant"), ("global", "Global")],
                default="tenant",
                max_length=10,
            ),
        ),
    ]
