/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-container": "#dae2fd",
        "tertiary-fixed-dim": "#7bd0ff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#b2e1ff",
        "tertiary": "#004e6b",
        "on-primary-container": "#dad7ff",
        "surface": "#f8f9ff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#3f465c",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed": "#0f0069",
        "on-secondary": "#ffffff",
        "on-background": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#131b2e",
        "inverse-surface": "#213145",
        "inverse-primary": "#c3c0ff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-tint": "#4d44e3",
        "on-surface": "#0b1c30",
        "secondary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "on-tertiary-fixed-variant": "#004c69",
        "surface-container-highest": "#d3e4fe",
        "on-tertiary-fixed": "#001e2c",
        "outline": "#777587",
        "surface-dim": "#cbdbf5",
        "primary-fixed": "#e2dfff",
        "tertiary-fixed": "#c4e7ff",
        "background": "#f8f9ff",
        "outline-variant": "#c7c4d8",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "tertiary-container": "#00678c",
        "on-surface-variant": "#464555",
        "surface-container-high": "#dce9ff",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary": "#ffffff",
        "secondary": "#565e74",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed-variant": "#3323cc",
        "primary-container": "#4f46e5",
        "primary": "#3525cd",
        "inverse-on-surface": "#eaf1ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "label-md": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
