# Generated by Django 4.2.30 on 2026-07-23 07:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('project_name', models.CharField(max_length=200)),
                ('objectives', models.TextField(blank=True)),
                ('team_members', models.TextField(help_text='Comma-separated team member names or JSON list')),
                ('expected_timeline', models.CharField(blank=True, max_length=100)),
                ('readiness_score', models.FloatField(blank=True, null=True)),
                ('ai_validation_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DISCOVERY', 'Discovery Phase'), ('VERIFICATION', 'Sequential Verification'), ('PROCESSING', 'AI Processing'), ('REVIEW', 'Final Review & Delivery'), ('COMPLETED', 'Completed')], default='DISCOVERY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_data', models.JSONField()),
                ('summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_report', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('BRD', 'Business Requirements Document'), ('FRD', 'Functional Requirements Document'), ('PRD', 'Product Requirements Document'), ('SOP', 'Standard Operating Procedure'), ('OTHER', 'Other')], max_length=10)),
                ('file', models.FileField(upload_to='uploads/documents/%Y/%m/%d/')),
                ('extracted_text', models.TextField(blank=True)),
                ('verification_status', models.CharField(default='pending', max_length=20)),
                ('missing_keywords', models.JSONField(default=list)),
                ('missing_sections', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
