# Generated by Django 6.0.7 on 2026-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expected_timeline',
            field=models.CharField(blank=True, help_text='Expected project duration or timeline', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='objectives',
            field=models.TextField(blank=True, help_text='Project objectives extracted from discovery'),
        ),
    ]
