# Generated by Django 4.2.30 on 2026-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
