# Generated by Django 6.0.7 on 2026-07-31 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_expected_timeline_project_objectives"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Task",
        ),
    ]
