# Generated by Django 4.2.30 on 2026-07-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_document_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_levels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
