# Generated by Django 6.0.7 on 2026-08-03 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='layers', max_length=50)),
                ('must_include', models.JSONField(blank=True, default=list, help_text='List of {id, text} required items')),
                ('recommended', models.JSONField(blank=True, default=list, help_text='List of {id, text} recommended items')),
                ('required_documents', models.JSONField(blank=True, default=list, help_text='List of {id, label} required document types')),
                ('required_count', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'level_modules',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='completed_levels',
            field=models.JSONField(blank=True, default=list, help_text='Levels that have passed verification'),
        ),
        migrations.AddField(
            model_name='project',
            name='current_level',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='project',
            name='industry',
            field=models.CharField(blank=True, help_text='Project industry', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='level_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Readiness score per level'),
        ),
        migrations.AddField(
            model_name='project',
            name='readiness_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.TextField(blank=True, help_text='Comma-separated team member names'),
        ),
        migrations.AddField(
            model_name='project',
            name='verification_report',
            field=models.JSONField(blank=True, help_text='Latest verification report', null=True),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_documents/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('doc_type', models.CharField(default='OTHER', max_length=20)),
                ('level', models.PositiveIntegerField(default=1)),
                ('extracted_text', models.TextField(blank=True)),
                ('verification_status', models.BooleanField(default=False)),
                ('verification_score', models.PositiveIntegerField(default=0)),
                ('missing_requirements', models.JSONField(blank=True, default=list, help_text='Required items missing from the document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
