# Generated by Django 4.2.30 on 2026-07-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_completed_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='level_scores',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
