# Generated by Django 4.2.30 on 2026-08-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_levelmodule_project_completed_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tag strings for categorizing the project'),
        ),
    ]
