# Generated by Django 4.2.30 on 2026-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_current_level_project_level_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
