# Generated by Django 4.2.30 on 2026-08-10 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
        ('projects', '0005_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='file_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='file_management.filecategory'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
