# Generated by Django 6.0.7 on 2026-07-29 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("company_management", "Company Management"),
                            ("user_management", "User Management"),
                            ("role_management", "Role Management"),
                            ("project_management", "Project Management"),
                            ("discovery", "Discovery"),
                            ("document_management", "Document Management"),
                            ("review_management", "Review Management"),
                            ("approval_management", "Approval Management"),
                            ("ai_chat", "AI Chat"),
                            ("knowledge_base", "Knowledge Base"),
                            ("reports", "Reports"),
                            ("audit_logs", "Audit Logs"),
                            ("settings", "Settings"),
                        ],
                        max_length=50,
                    ),
                ),
                ("can_view", models.BooleanField(default=False)),
                ("can_create", models.BooleanField(default=False)),
                ("can_update", models.BooleanField(default=False)),
                ("can_delete", models.BooleanField(default=False)),
                ("can_review", models.BooleanField(default=False)),
                ("can_approve", models.BooleanField(default=False)),
                ("can_export", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="roles.role",
                    ),
                ),
            ],
            options={
                "db_table": "permissions",
                "ordering": ["feature"],
                "unique_together": {("role", "feature")},
            },
        ),
    ]
