# Generated by Django 4.2.30 on 2026-08-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='feature',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('company_management', 'Company Management'), ('user_management', 'User Management'), ('role_management', 'Role Management'), ('project_management', 'Project Management'), ('discovery', 'Discovery'), ('document_management', 'Document Management'), ('review_management', 'Review Management'), ('approval_management', 'Approval Management'), ('ai_chat', 'AI Chat'), ('knowledge_base', 'Knowledge Base'), ('reports', 'Reports'), ('audit_logs', 'Audit Logs'), ('settings', 'Settings'), ('login_history', 'Login History')], max_length=50),
        ),
    ]
