# Generated by Django 4.2.30 on 2026-08-06 05:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_status_companysettings_companyonboarding'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_plan_gated', models.BooleanField(default=True, help_text='Requires allows_<code> on the plan when enabled.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(db_index=True, max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='companies.company')),
            ],
            options={
                'db_table': 'usage_records',
                'ordering': ['-period_start'],
                'unique_together': {('company', 'feature', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='CompanyFeatureOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='companies.company')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_overrides', to='subscriptions.featureflag')),
            ],
            options={
                'db_table': 'company_feature_overrides',
                'unique_together': {('company', 'feature')},
            },
        ),
    ]
