# Generated by Django 6.0.7 on 2026-07-31 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('failed_login', 'Failed Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('export', 'Export'), ('password_change', 'Password Change'), ('session_created', 'Session Created'), ('session_revoked', 'Session Revoked'), ('sessions_revoked', 'Sessions Revoked'), ('soft_delete', 'Soft Delete'), ('permission_change', 'Permission Change')], max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
