# Generated by Django 6.0.7 on 2026-07-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_version',
            field=models.PositiveSmallIntegerField(default=0, help_text='Incremented on every password change. JWTs carry the version they were issued with; tokens with a stale version are rejected.'),
        ),
    ]
