# Generated by Django 4.2.30 on 2026-08-10 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0005_project_tags'),
        ('companies', '0002_company_status_companysettings_companyonboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_limit_bytes', models.BigIntegerField(default=5368709120)),
                ('enforced', models.BooleanField(default=True, help_text='When enabled, uploads over the limit are rejected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_quota', to='companies.company')),
            ],
            options={
                'db_table': 'storage_quotas',
            },
        ),
        migrations.CreateModel(
            name='FileScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('infected', 'Infected'), ('error', 'Scan Error')], default='pending', max_length=20)),
                ('scanner', models.CharField(blank=True, help_text='Scanner backend that produced the result (e.g. clamav, signature)', max_length=50)),
                ('signature', models.CharField(blank=True, help_text='Detection signature name when a threat is found', max_length=255)),
                ('findings', models.JSONField(blank=True, default=dict, help_text='Structured scan details returned by the scanner')),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan', to='projects.projectdocument')),
            ],
            options={
                'db_table': 'file_scans',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(blank=True, help_text='Role key (e.g. client_admin) the rule applies to', max_length=50)),
                ('permission', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('delete', 'Delete'), ('manage', 'Manage')], max_length=20)),
                ('allow', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='projects.projectdocument')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_permissions',
                'ordering': ['file', 'permission', 'role_key'],
            },
        ),
        migrations.CreateModel(
            name='FileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('color', models.CharField(default='#2563eb', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Material symbol name shown in the UI', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_categories', to='companies.company')),
            ],
            options={
                'db_table': 'file_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='filepermission',
            constraint=models.UniqueConstraint(fields=('file', 'user', 'role_key', 'permission'), name='uniq_file_permission_rule'),
        ),
        migrations.AddConstraint(
            model_name='filecategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_file_category_company_name'),
        ),
    ]
