# Generated by Django 4.2.30 on 2026-08-12 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectdocument_file_category_and_more'),
        ('tasks', '0002_taskattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailed_tasks', to='projects.project'),
        ),
    ]
