export const LEVEL_MODULES = [
  {
    level: 1,
    title: "Discovery & Evaluation",
    description: "Evaluate use cases and capture discovery context - problem statements, expected outcomes, data sources and current process gaps - before shortlisting candidate AI use cases.",
    icon: "explore",
    must_include: [
      { id: 101, text: "Use Cases" },
      { id: 102, text: "Problem statements" },
      { id: 103, text: "Expected outcomes" },
      { id: 104, text: "Department owner" },
      { id: 105, text: "Data sources" },
      { id: 106, text: "Pain points & current process gaps" },
    ],
    recommended: [
      { id: 107, text: "Use Case Evaluation Sheet - data availability, management priority, third-party dependency, feasibility & ROI, operational readiness" },
      { id: 108, text: "Use Case Shortlisting Report - scoring summary, final shortlisted use cases, rationale for selection" },
    ],
    required_documents: [
      { id: "d1-1", doc_type: "USE-CASES", label: "Use Cases" },
      { id: "d1-2", doc_type: "EVAL-SHEET", label: "Use Case Evaluation Sheet" },
      { id: "d1-3", doc_type: "SHORTLIST", label: "Use Case Shortlisting Report" },
    ],
    required_count: 6,
  },
  {
    level: 2,
    title: "User & Experience",
    description: "Document the people who will use the product - personas, journeys and flows - so requirements reflect real user needs and AI intervention opportunities.",
    icon: "person",
    must_include: [
      { id: 201, text: "User Personas - user types, roles & responsibilities" },
      { id: 202, text: "User motivations" },
      { id: 203, text: "Pain points & frustrations" },
      { id: 204, text: "Expected benefits" },
      { id: 205, text: "User-Journeys - step-by-step journey, touchpoints, emotions" },
      { id: 206, text: "Opportunities for AI intervention" },
    ],
    recommended: [
      { id: 207, text: "User-Flows - detailed workflow diagrams, inputs/outputs, decision points, exceptions" },
      { id: 208, text: "User-Journeys - emotions/frustrations at each touchpoint" },
    ],
    required_documents: [
      { id: "d2-1", doc_type: "PERSONAS", label: "User Personas" },
      { id: "d2-2", doc_type: "USER-JOURNEYS", label: "User-Journeys" },
      { id: "d2-3", doc_type: "USER-FLOWS", label: "User-Flows" },
    ],
    required_count: 6,
  },
  {
    level: 3,
    title: "Requirements & Prioritization",
    description: "Define business, functional and product requirements - BRD, FRD, PRD, NFRs and feature prioritization - that govern scope and acceptance criteria.",
    icon: "description",
    must_include: [
      { id: 301, text: "BRD - business problem, scope, success metrics, stakeholders" },
      { id: 302, text: "FRD - functional flows, system behavior, business rules, acceptance criteria" },
      { id: 303, text: "Feature Prioritization - MoSCoW (must/should/could/won't) scoring" },
      { id: 304, text: "NFR - performance, scalability, security, availability, compliance" },
      { id: 305, text: "PRD - product vision, feature list, release plan" },
    ],
    recommended: [
      { id: 306, text: "Traceability matrix across BRD, FRD, PRD and test cases" },
      { id: 307, text: "Acceptance criteria mapping for every functional requirement" },
    ],
    required_documents: [
      { id: "d3-1", doc_type: "BRD", label: "BRD" },
      { id: "d3-2", doc_type: "FRD", label: "FRD" },
      { id: "d3-3", doc_type: "FEATURE-PRIO", label: "Feature Prioritization" },
      { id: "d3-4", doc_type: "NFR", label: "NFR" },
      { id: "d3-5", doc_type: "PRD", label: "PRD" },
    ],
    required_count: 5,
  },
  {
    level: 4,
    title: "Estimation & Planning",
    description: "Estimate effort and plan delivery - module-wise effort, function point estimation, project plan with milestones and sprints, and a RACI matrix.",
    icon: "schema",
    must_include: [
      { id: 401, text: "Effort Estimation - module-wise, total hours, assumptions" },
      { id: 402, text: "Function Point Estimation - function point breakdown & complexity scoring" },
      { id: 403, text: "Project Plan / Timeline - milestones, sprints, dependencies" },
      { id: 404, text: "RACI Matrix - responsible, accountable, consulted, informed" },
    ],
    recommended: [
      { id: 405, text: "Resource allocation & capacity planning across sprints" },
      { id: 406, text: "Risk register with mitigation owners and dates" },
    ],
    required_documents: [
      { id: "d4-1", doc_type: "EFFORT-EST", label: "Effort Estimation" },
      { id: "d4-2", doc_type: "FP-EST", label: "Function Point Estimation" },
      { id: "d4-3", doc_type: "PROJECT-PLAN", label: "Project Plan / Timeline" },
      { id: "d4-4", doc_type: "RACI", label: "RACI Matrix" },
    ],
    required_count: 4,
  },
  {
    level: 5,
    title: "Architecture & Technical",
    description: "Specify the technical solution - high-level and low-level architecture, the AI architecture blueprint and the API specification.",
    icon: "account_tree",
    must_include: [
      { id: 501, text: "High-Level Architecture (HLA) - system overview, major components, integration points" },
      { id: 502, text: "Low-Level Architecture (LLA) - component design, database schema, data flow" },
      { id: 503, text: "AI Architecture Blueprint - RAG architecture, prompt flow design, model selection rationale" },
      { id: 504, text: "API Specification - endpoints, schemas, authentication, error codes" },
    ],
    recommended: [
      { id: 505, text: "Deployment model (cloud, on-prem, hybrid) with environments" },
      { id: 506, text: "Third-party dependency & data flow diagram" },
    ],
    required_documents: [
      { id: "d5-1", doc_type: "HLA", label: "High-Level Architecture (HLA)" },
      { id: "d5-2", doc_type: "LLA", label: "Low-Level Architecture (LLA)" },
      { id: "d5-3", doc_type: "AI-ARCH", label: "AI Architecture Blueprint" },
      { id: "d5-4", doc_type: "API-SPEC", label: "API Specification" },
    ],
    required_count: 4,
  },
  {
    level: 6,
    title: "Security, Guardrails & Compliance",
    description: "Document the security policy, AI guardrails, secrets management and compliance coverage required for the solution.",
    icon: "security",
    must_include: [
      { id: 601, text: "AI Security Policy - data handling rules, PII protection, access control" },
      { id: 602, text: "Guardrails - prompt filtering, output validation, hallucination control, safety rules" },
      { id: 603, text: "Azure Key Vault Secrets Map - secrets list, rotation policy, access matrix" },
      { id: 604, text: "Compliance Checklist - ISO/SOC alignment, IT policies, audit requirements" },
    ],
    recommended: [
      { id: 605, text: "Security review sign-off & approval record" },
      { id: 606, text: "Responsible AI ethics checklist" },
    ],
    required_documents: [
      { id: "d6-1", doc_type: "AI-SECURITY", label: "AI Security Policy" },
      { id: "d6-2", doc_type: "GUARDRAILS", label: "Guardrails Document" },
      { id: "d6-3", doc_type: "KEY-VAULT", label: "Azure Key Vault Secrets Map" },
      { id: "d6-4", doc_type: "COMPLIANCE", label: "Compliance Checklist" },
    ],
    required_count: 4,
  },
  {
    level: 7,
    title: "Monitoring, Evaluation & Observability",
    description: "Define product and AI metrics, observability dashboards, LLM evaluation and incident management for the solution.",
    icon: "monitoring",
    must_include: [
      { id: 701, text: "Metrics Document - product usage & adoption metrics, AI performance & business impact metrics" },
      { id: 702, text: "Monitoring & Observability - dashboards (Azure Monitor, Prometheus, Grafana), logging, alerting" },
      { id: 703, text: "LLM Evaluation - accuracy, relevance, hallucination rate" },
      { id: 704, text: "Incident & Error Management SOP - escalation flow, severity levels, resolution steps" },
    ],
    recommended: [
      { id: 705, text: "Cost monitoring - token usage and infrastructure cost dashboards" },
      { id: 706, text: "SLO/SLI definitions with alert thresholds" },
    ],
    required_documents: [
      { id: "d7-1", doc_type: "METRICS", label: "Metrics Document" },
      { id: "d7-2", doc_type: "MONITORING", label: "Monitoring & Observability Plan" },
      { id: "d7-3", doc_type: "LLM-EVAL", label: "LLM Evaluation Report" },
      { id: "d7-4", doc_type: "INCIDENT-SOP", label: "Incident & Error Management SOP" },
    ],
    required_count: 4,
  },
  {
    level: 8,
    title: "Deployment, Release & Adoption",
    description: "Plan deployment and release, and drive adoption with training, onboarding and adoption metrics.",
    icon: "rocket_launch",
    must_include: [
      { id: 801, text: "Deployment Guide - environment setup, release steps, rollback plan" },
      { id: 802, text: "Release Notes - version changes, fixes, known issues" },
      { id: 803, text: "Change Log - approved changes, dates, owners" },
      { id: 804, text: "Training Manual - admin & user guides" },
    ],
    recommended: [
      { id: 805, text: "Onboarding Guide - access instructions, support channels" },
      { id: 806, text: "Adoption Dashboard - DAU/MAU, feature usage, feedback scores" },
    ],
    required_documents: [
      { id: "d8-1", doc_type: "DEPLOY-GUIDE", label: "Deployment Guide" },
      { id: "d8-2", doc_type: "RELEASE-NOTES", label: "Release Notes" },
      { id: "d8-3", doc_type: "CHANGE-LOG", label: "Change Log" },
      { id: "d8-4", doc_type: "TRAINING", label: "Training Manual" },
      { id: "d8-5", doc_type: "ONBOARDING", label: "Onboarding Guide" },
      { id: "d8-6", doc_type: "ADOPTION", label: "Adoption Dashboard" },
    ],
    required_count: 6,
  },
  {
    level: 9,
    title: "Governance & Long-Term AI Strategy",
    description: "Establish governance, oversight and a long-term AI strategy for continued operation and expansion.",
    icon: "account_balance",
    must_include: [
      { id: 901, text: "AI Governance Framework - roles, responsibilities, review cycles" },
      { id: 902, text: "Steering Committee Charter - meeting cadence, decision rights, escalation path" },
      { id: 903, text: "AI Roadmap - quarterly roadmap & expansion plan" },
      { id: 904, text: "Model Retraining & Drift Management - model versioning, retraining triggers" },
    ],
    recommended: [
      { id: 905, text: "Future use cases & opportunity pipeline" },
      { id: 906, text: "AI investment & ROI review template" },
    ],
    required_documents: [
      { id: "d9-1", doc_type: "GOVERNANCE", label: "AI Governance Framework" },
      { id: "d9-2", doc_type: "STEERING-CHARTER", label: "Steering Committee Charter" },
      { id: "d9-3", doc_type: "AI-ROADMAP", label: "AI Roadmap" },
      { id: "d9-4", doc_type: "DRIFT-PLAN", label: "Model Retraining & Drift Management Plan" },
    ],
    required_count: 4,
  },
  {
    level: 10,
    title: "Testing & Quality Engineering",
    description: "Validate the solution end-to-end with a full test and quality engineering suite.",
    icon: "fact_check",
    must_include: [
      { id: 1001, text: "Test Strategy - scope, test types, tools, entry/exit criteria" },
      { id: 1002, text: "Functional & API Test Cases" },
      { id: 1003, text: "Regression Test Suite - critical workflows, AI prompt & RAG regression" },
      { id: 1004, text: "Performance Test Report - load, stress, latency, throughput" },
      { id: 1005, text: "Security Test Report - vulnerability scan, pen test, RBAC, OWASP" },
      { id: 1006, text: "LLM/RAG Evaluation Report - accuracy, relevance, hallucination, safety, retrieval quality" },
    ],
    recommended: [
      { id: 1007, text: "Acceptance criteria mapping across all levels" },
      { id: 1008, text: "Guardrail validation & prompt regression results" },
    ],
    required_documents: [
      { id: "d10-1", doc_type: "TEST-STRATEGY", label: "Test Strategy" },
      { id: "d10-2", doc_type: "TEST-CASES", label: "Functional & API Test Cases" },
      { id: "d10-3", doc_type: "REGRESSION", label: "Regression Test Suite" },
      { id: "d10-4", doc_type: "PERF-REPORT", label: "Performance Test Report" },
      { id: "d10-5", doc_type: "SEC-TEST", label: "Security Test Report" },
      { id: "d10-6", doc_type: "RAG-EVAL", label: "LLM/RAG Evaluation Report" },
    ],
    required_count: 6,
  },
];

export const EXECUTIVE_SUMMARY_DOCS = [
  "Use Cases",
  "Personas",
  "User Journeys",
  "User Flows",
  "Feature Prioritization (FPE)",
  "NFRs",
  "BRD + FRD + PRD",
  "Effort Estimation + Function Point Estimation",
  "Metrics Document",
  "Architecture (HLA + LLA)",
  "Security & Guardrails Document",
  "Monitoring & Evaluation Plan",
  "Deployment Guide",
  "Governance Framework",
  "Testing and Quality Engineering Documents",
];

export const DOC_TYPE_OPTIONS = [
  { value: "USE-CASES", label: "Use Cases" },
  { value: "EVAL-SHEET", label: "Use Case Evaluation Sheet" },
  { value: "SHORTLIST", label: "Use Case Shortlisting Report" },
  { value: "PERSONAS", label: "User Personas" },
  { value: "USER-JOURNEYS", label: "User-Journeys" },
  { value: "USER-FLOWS", label: "User-Flows" },
  { value: "BRD", label: "Business Requirements Document" },
  { value: "FRD", label: "Functional Requirements Document" },
  { value: "PRD", label: "Product Requirements Document" },
  { value: "FEATURE-PRIO", label: "Feature Prioritization" },
  { value: "NFR", label: "Non-Functional Requirements" },
  { value: "EFFORT-EST", label: "Effort Estimation" },
  { value: "FP-EST", label: "Function Point Estimation" },
  { value: "PROJECT-PLAN", label: "Project Plan / Timeline" },
  { value: "RACI", label: "RACI Matrix" },
  { value: "HLA", label: "High-Level Architecture" },
  { value: "LLA", label: "Low-Level Architecture" },
  { value: "AI-ARCH", label: "AI Architecture Blueprint" },
  { value: "API-SPEC", label: "API Specification" },
  { value: "AI-SECURITY", label: "AI Security Policy" },
  { value: "GUARDRAILS", label: "Guardrails Document" },
  { value: "KEY-VAULT", label: "Azure Key Vault Secrets Map" },
  { value: "COMPLIANCE", label: "Compliance Checklist" },
  { value: "METRICS", label: "Metrics Document" },
  { value: "MONITORING", label: "Monitoring & Observability Plan" },
  { value: "LLM-EVAL", label: "LLM Evaluation Report" },
  { value: "INCIDENT-SOP", label: "Incident & Error Management SOP" },
  { value: "DEPLOY-GUIDE", label: "Deployment Guide" },
  { value: "RELEASE-NOTES", label: "Release Notes" },
  { value: "CHANGE-LOG", label: "Change Log" },
  { value: "TRAINING", label: "Training Manual" },
  { value: "ONBOARDING", label: "Onboarding Guide" },
  { value: "ADOPTION", label: "Adoption Dashboard" },
  { value: "GOVERNANCE", label: "AI Governance Framework" },
  { value: "STEERING-CHARTER", label: "Steering Committee Charter" },
  { value: "AI-ROADMAP", label: "AI Roadmap" },
  { value: "DRIFT-PLAN", label: "Model Retraining & Drift Management Plan" },
  { value: "TEST-STRATEGY", label: "Test Strategy" },
  { value: "TEST-CASES", label: "Functional & API Test Cases" },
  { value: "REGRESSION", label: "Regression Test Suite" },
  { value: "PERF-REPORT", label: "Performance Test Report" },
  { value: "SEC-TEST", label: "Security Test Report" },
  { value: "RAG-EVAL", label: "LLM/RAG Evaluation Report" },
  { value: "SOP", label: "Standard Operating Procedure" },
  { value: "OTHER", label: "Other" },
];
