export const ROLES_DATA = {
  super_admin: {
    id: "super_admin",
    name: "Alexander Vance",
    email: "superadmin@requirementai.com",
    role: "admin", // maps to high-level 'admin' or 'client' structure
    assigned_role: "Super Admin",
    company: "RequirementAI Consulting (Internal)",
    department: "Platform Management",
    project_access: "All Projects",
    dashboard_name: "Platform Dashboard",
    permissions: {
      upload: true,
      review: true,
      approve: true,
      manage_users: true,
      manage_projects: true,
      platform_settings: true,
    },
    access_checklist: [
      "Manage Companies",
      "Manage Subscriptions",
      "Configure AI Models",
      "Configure Global Templates",
      "Manage Security",
      "Audit Logs",
      "Platform Analytics",
      "All Projects"
    ],
    password: "password123"
  },
  company_admin: {
    id: "company_admin",
    name: "Sarah Chen",
    email: "companyadmin@requirementai.com",
    role: "admin",
    assigned_role: "Company Admin",
    company: "RequirementAI Consulting",
    department: "Administration",
    project_access: "All Projects",
    dashboard_name: "Company Dashboard",
    permissions: {
      upload: true,
      review: true,
      approve: true,
      manage_users: true,
      manage_projects: true,
      platform_settings: false,
    },
    access_checklist: [
      "Create Projects",
      "Edit Projects",
      "Archive Projects",
      "Invite Employees",
      "Assign Roles",
      "Department Management",
      "Company Reports"
    ],
    password: "password123"
  },
  project_manager: {
    id: "project_manager",
    name: "Michael Vance",
    email: "pm@requirementai.com",
    role: "admin",
    assigned_role: "Project Manager",
    company: "RequirementAI Consulting",
    department: "Project Management Office",
    project_access: "All Projects",
    dashboard_name: "Project Dashboard",
    permissions: {
      upload: true,
      review: true,
      approve: true,
      manage_users: false,
      manage_projects: true,
      platform_settings: false,
    },
    access_checklist: [
      "Create Project",
      "Manage Timeline",
      "Assign Tasks",
      "View All Documents",
      "Review Documents",
      "Approve Deliverables",
      "Project Reports"
    ],
    password: "password123"
  },
  business_analyst: {
    id: "business_analyst",
    name: "Emily Watson",
    email: "ba@requirementai.com",
    role: "admin",
    assigned_role: "Business Analyst",
    company: "RequirementAI Consulting",
    department: "Business Analysis",
    project_access: "Enterprise Migration, RAG Implementation",
    dashboard_name: "Discovery Dashboard",
    permissions: {
      upload: true,
      review: true,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "Upload Discovery Documents",
      "Upload BRD",
      "Upload FRD",
      "Upload Personas",
      "Upload User Stories",
      "Upload Process Flow",
      "Respond to AI Validation",
      "View Readiness Score"
    ],
    password: "password123"
  },
  solution_architect: {
    id: "solution_architect",
    name: "David Kross",
    email: "architect@requirementai.com",
    role: "admin",
    assigned_role: "Solution Architect",
    company: "RequirementAI Consulting",
    department: "Architecture & Integration",
    project_access: "Enterprise Migration, Cloud Native Analytics",
    dashboard_name: "Architecture Dashboard",
    permissions: {
      upload: true,
      review: true,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "Upload Architecture",
      "Upload API Design",
      "Upload Integration Documents",
      "Upload Database Design",
      "Review Technical Documents"
    ],
    password: "password123"
  },
  ai_ml_engineer: {
    id: "ai_ml_engineer",
    name: "Elena Rostova",
    email: "ai_eng@requirementai.com",
    role: "admin",
    assigned_role: "AI/ML Engineer",
    company: "RequirementAI Consulting",
    department: "Artificial Intelligence",
    project_access: "RAG Implementation, LLM Fine-Tuning",
    dashboard_name: "AI Dashboard",
    permissions: {
      upload: true,
      review: true,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "Configure AI Models",
      "Configure Prompt Library",
      "Manage Embeddings",
      "View AI Logs",
      "View Validation Results"
    ],
    password: "password123"
  },
  backend_developer: {
    id: "backend_developer",
    name: "Marcus Aurelius",
    email: "backend@requirementai.com",
    role: "admin",
    assigned_role: "Backend Developer",
    company: "RequirementAI Consulting",
    department: "Backend Engineering",
    project_access: "RAG Implementation, Enterprise Migration",
    dashboard_name: "Development Dashboard",
    permissions: {
      upload: true,
      review: false,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "API Documentation",
      "Technical Documents",
      "Integration Documents",
      "Assigned Tasks"
    ],
    password: "password123"
  },
  frontend_developer: {
    id: "frontend_developer",
    name: "Lisa Simpson",
    email: "frontend@requirementai.com",
    role: "admin",
    assigned_role: "Frontend Developer",
    company: "RequirementAI Consulting",
    department: "Frontend Engineering",
    project_access: "RAG Implementation, User Dashboard Refresh",
    dashboard_name: "UI Dashboard",
    permissions: {
      upload: true,
      review: false,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "UI Documents",
      "Design Files",
      "Assigned Tasks"
    ],
    password: "password123"
  },
  qa_test_engineer: {
    id: "qa_test_engineer",
    name: "Thomas Edison",
    email: "qa@requirementai.com",
    role: "admin",
    assigned_role: "QA / Test Engineer",
    company: "RequirementAI Consulting",
    department: "Quality Assurance",
    project_access: "All Active QA Pipelines",
    dashboard_name: "QA Dashboard",
    permissions: {
      upload: true,
      review: true,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "Upload Test Cases",
      "Upload Test Reports",
      "Upload UAT",
      "Verify Requirements",
      "Raise Defects"
    ],
    password: "password123"
  },
  security_consultant: {
    id: "security_consultant",
    name: "Grace Hopper",
    email: "security@requirementai.com",
    role: "admin",
    assigned_role: "Security Consultant",
    company: "RequirementAI Consulting",
    department: "Information Security",
    project_access: "Secure Cloud Migration",
    dashboard_name: "Security Dashboard",
    permissions: {
      upload: true,
      review: true,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "Upload Security Reports",
      "Risk Assessment",
      "Compliance Review",
      "Review Architecture"
    ],
    password: "password123"
  },
  devops_engineer: {
    id: "devops_engineer",
    name: "Alan Turing",
    email: "devops@requirementai.com",
    role: "admin",
    assigned_role: "DevOps Engineer",
    company: "RequirementAI Consulting",
    department: "DevOps & Infrastructure",
    project_access: "Kubernetes Cluster Deployments",
    dashboard_name: "DevOps Dashboard",
    permissions: {
      upload: true,
      review: false,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "Deployment Documents",
      "Release Notes",
      "Infrastructure Documents",
      "Environment Configuration"
    ],
    password: "password123"
  },
  document_reviewer: {
    id: "document_reviewer",
    name: "Ada Lovelace",
    email: "reviewer@requirementai.com",
    role: "admin",
    assigned_role: "Document Reviewer",
    company: "RequirementAI Consulting",
    department: "Quality & Review",
    project_access: "All Deliverable Reviews",
    dashboard_name: "Review Dashboard",
    permissions: {
      upload: false,
      review: true,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "Review Documents",
      "Add Comments",
      "Request Changes",
      "Verify Formatting"
    ],
    password: "password123"
  },
  client_admin: {
    id: "client_admin",
    name: "John Smith",
    email: "client_admin@acmecorp.com",
    role: "client",
    assigned_role: "Client Admin",
    company: "Acme Corp",
    department: "Client Operations",
    project_access: "Acme ERP Sync",
    dashboard_name: "Client Dashboard",
    permissions: {
      upload: true,
      review: true,
      approve: false,
      manage_users: true,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "View Projects",
      "Upload Company Documents",
      "Invite Client Users",
      "Track Project Status"
    ],
    password: "password123"
  },
  client_sme: {
    id: "client_sme",
    name: "Robert Kiyosaki",
    email: "client_sme@acmecorp.com",
    role: "client",
    assigned_role: "Client Department Owner (SME)",
    company: "Acme Corp",
    department: "Client Business Operations",
    project_access: "Acme ERP Sync",
    dashboard_name: "Department Dashboard",
    permissions: {
      upload: true,
      review: false,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "Upload SOPs",
      "Upload Process Documents",
      "Upload Sample Files",
      "Answer AI Questions",
      "Upload Revised Documents"
    ],
    password: "password123"
  },
  client_reviewer: {
    id: "client_reviewer",
    name: "Arthur Pendragon",
    email: "client_reviewer@acmecorp.com",
    role: "client",
    assigned_role: "Client Reviewer",
    company: "Acme Corp",
    department: "Client Quality & Review",
    project_access: "Acme ERP Sync",
    dashboard_name: "Review Dashboard",
    permissions: {
      upload: false,
      review: true,
      approve: true,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "Review Documents",
      "Add Comments",
      "Request Changes",
      "Approve Documents"
    ],
    password: "password123"
  },
  business_sponsor: {
    id: "business_sponsor",
    name: "Bruce Wayne",
    email: "sponsor@acmecorp.com",
    role: "client",
    assigned_role: "Business Sponsor",
    company: "Acme Corp",
    department: "Executive Sponsor Group",
    project_access: "Acme ERP Sync",
    dashboard_name: "Executive Dashboard",
    permissions: {
      upload: false,
      review: true,
      approve: true,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "Executive Reports",
      "Milestone Status",
      "Budget Overview",
      "Final Approval"
    ],
    password: "password123"
  },
  viewer: {
    id: "viewer",
    name: "Clark Kent",
    email: "viewer@acmecorp.com",
    role: "client",
    assigned_role: "Viewer",
    company: "Acme Corp",
    department: "General Audience",
    project_access: "Acme ERP Sync",
    dashboard_name: "Read-Only Dashboard",
    permissions: {
      upload: false,
      review: false,
      approve: false,
      manage_users: false,
      manage_projects: false,
      platform_settings: false,
    },
    access_checklist: [
      "View Approved Documents",
      "View Reports",
      "View Dashboard"
    ],
    password: "password123"
  }
};
