# Generated by Django 6.0.7 on 2026-07-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_key",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("company_admin", "Company Admin"),
                            ("project_manager", "Project Manager"),
                            ("business_analyst", "Business Analyst"),
                            ("solution_architect", "Solution Architect"),
                            (
                                "ai_ml_engineer",
                                "Artificial Intelligence/Machine Learning Engineer",
                            ),
                            ("backend_developer", "Backend Developer"),
                            ("frontend_developer", "Frontend Developer"),
                            ("qa_test_engineer", "Quality Assurance/Test Engineer"),
                            ("security_consultant", "Security Consultant"),
                            ("devops_engineer", "DevOps Engineer"),
                            ("document_reviewer", "Document Reviewer"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "roles",
                "ordering": ["display_name"],
            },
        ),
    ]
