# Generated by Django 4.2.30 on 2026-08-13 06:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIInterventionPainArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('process_activity', models.CharField(blank=True, default='', max_length=255)),
                ('pain_area', models.TextField(blank=True, default='')),
                ('current_method', models.TextField(blank=True, default='')),
                ('frequency', models.CharField(blank=True, default='', max_length=100)),
                ('time_spent_hrs', models.FloatField(blank=True, null=True)),
                ('impact_area', models.CharField(blank=True, default='', max_length=255)),
                ('ai_intervention', models.TextField(blank=True, default='')),
                ('expected_benefit', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('feasibility', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled')], default='Open', max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Intervention Pain Area',
                'verbose_name_plural': 'AI Intervention Pain Areas',
                'db_table': 'ai_intervention_pain_areas_tracker',
                'ordering': ['-date', '-created_at'],
                'managed': False,
            },
        ),
    ]
