# Generated by Django 6.0.7 on 2026-07-29 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discovery",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="discovery",
            old_name="assumptions",
            new_name="remarks",
        ),
        migrations.RemoveField(
            model_name="discovery",
            name="business_goal",
        ),
        migrations.RemoveField(
            model_name="discovery",
            name="business_problem",
        ),
        migrations.RemoveField(
            model_name="discovery",
            name="constraints",
        ),
        migrations.RemoveField(
            model_name="discovery",
            name="current_process",
        ),
        migrations.RemoveField(
            model_name="discovery",
            name="document",
        ),
        migrations.RemoveField(
            model_name="discovery",
            name="future_process",
        ),
        migrations.RemoveField(
            model_name="discovery",
            name="pain_points",
        ),
        migrations.RemoveField(
            model_name="discovery",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="discovery",
            name="success_criteria",
        ),
        migrations.AddField(
            model_name="discovery",
            name="input_type",
            field=models.CharField(
                choices=[("text", "Text"), ("pdf", "PDF")],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="discovery",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="discovery",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discoveries_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="discovery",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("submitted", "Submitted"),
                    ("review", "Under Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="discovery",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discoveries_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DiscoveryDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_file", models.FileField(upload_to="discovery/")),
                ("original_filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField()),
                ("extracted_text", models.TextField(blank=True)),
                ("ai_summary", models.TextField(blank=True)),
                ("total_pages", models.PositiveIntegerField(default=0)),
                ("upload_time", models.DateTimeField(auto_now_add=True)),
                (
                    "discovery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to="discovery.discovery",
                    ),
                ),
            ],
            options={
                "db_table": "discovery_documents",
            },
        ),
        migrations.CreateModel(
            name="DiscoveryText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("executive_summary", models.TextField(blank=True)),
                ("business_problem", models.TextField()),
                ("business_goal", models.TextField()),
                ("current_process", models.TextField()),
                ("future_process", models.TextField(blank=True)),
                ("stakeholders", models.TextField(blank=True)),
                ("departments", models.TextField(blank=True)),
                ("users", models.TextField(blank=True)),
                ("assumptions", models.TextField(blank=True)),
                ("constraints", models.TextField(blank=True)),
                ("pain_points", models.TextField()),
                ("opportunities", models.TextField(blank=True)),
                ("functional_requirements", models.TextField(blank=True)),
                ("non_functional_requirements", models.TextField(blank=True)),
                ("risks", models.TextField(blank=True)),
                ("dependencies", models.TextField(blank=True)),
                ("success_criteria", models.TextField(blank=True)),
                ("expected_roi", models.TextField(blank=True)),
                ("additional_notes", models.TextField(blank=True)),
                (
                    "discovery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_content",
                        to="discovery.discovery",
                    ),
                ),
            ],
            options={
                "db_table": "discovery_text",
            },
        ),
    ]
