# Generated by Django 6.0.7 on 2026-07-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_alter_discovery_options_and_more'),
        ('projects', '0002_project_expected_timeline_project_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='discovery',
            name='ai_processed',
            field=models.BooleanField(default=False, help_text='Whether AI has processed this discovery'),
        ),
        migrations.AddField(
            model_name='discovery',
            name='completeness_score',
            field=models.PositiveIntegerField(default=0, help_text='Auto-calculated completeness percentage 0-100'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('needs_info', 'Needs More Info'), ('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
