# Generated by Django 4.2.30 on 2026-08-06 05:42

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('time_format', models.CharField(default='HH:mm', max_length=20)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7, validators=[core.validators.validate_hex_color])),
                ('secondary_color', models.CharField(default='#64748b', max_length=7, validators=[core.validators.validate_hex_color])),
                ('accent_color', models.CharField(default='#0ea5e9', max_length=7, validators=[core.validators.validate_hex_color])),
                ('font_family', models.CharField(default='Inter', max_length=100)),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='company_favicons/')),
                ('custom_css', models.TextField(blank=True)),
                ('branding_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Setting',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'company_settings',
            },
        ),
        migrations.CreateModel(
            name='CompanyOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_completed', models.BooleanField(default=False)),
                ('branding_completed', models.BooleanField(default=False)),
                ('members_added', models.BooleanField(default=False)),
                ('subscription_active', models.BooleanField(default=False)),
                ('first_project_created', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Onboarding',
                'verbose_name_plural': 'Company Onboarding',
                'db_table': 'company_onboarding',
            },
        ),
    ]
