# Generated by Django 6.0.7 on 2026-07-29 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('overall_score', models.PositiveIntegerField(blank=True, choices=[(1, 'Level 1 - Initial'), (2, 'Level 2 - Managed'), (3, 'Level 3 - Defined'), (4, 'Level 4 - Quantitatively Managed'), (5, 'Level 5 - Optimizing')], null=True)),
                ('data_readiness_score', models.PositiveIntegerField(blank=True, choices=[(1, 'Level 1 - Initial'), (2, 'Level 2 - Managed'), (3, 'Level 3 - Defined'), (4, 'Level 4 - Quantitatively Managed'), (5, 'Level 5 - Optimizing')], null=True)),
                ('infrastructure_score', models.PositiveIntegerField(blank=True, choices=[(1, 'Level 1 - Initial'), (2, 'Level 2 - Managed'), (3, 'Level 3 - Defined'), (4, 'Level 4 - Quantitatively Managed'), (5, 'Level 5 - Optimizing')], null=True)),
                ('talent_score', models.PositiveIntegerField(blank=True, choices=[(1, 'Level 1 - Initial'), (2, 'Level 2 - Managed'), (3, 'Level 3 - Defined'), (4, 'Level 4 - Quantitatively Managed'), (5, 'Level 5 - Optimizing')], null=True)),
                ('strategy_score', models.PositiveIntegerField(blank=True, choices=[(1, 'Level 1 - Initial'), (2, 'Level 2 - Managed'), (3, 'Level 3 - Defined'), (4, 'Level 4 - Quantitatively Managed'), (5, 'Level 5 - Optimizing')], null=True)),
                ('executive_summary', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assessments_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assessments_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessment', to='projects.project')),
            ],
            options={
                'db_table': 'ai_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('business_value', models.TextField(blank=True)),
                ('technical_feasibility', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('evaluated', 'Evaluated'), ('approved', 'Approved'), ('in_development', 'In Development'), ('deployed', 'Deployed')], default='identified', max_length=20)),
                ('estimated_roi', models.CharField(blank=True, max_length=255)),
                ('estimated_timeline', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='ai_engine.aiassessment')),
            ],
            options={
                'db_table': 'ai_use_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
