# Generated by Django 4.2.30 on 2026-08-07 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_status_companysettings_companyonboarding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The user who performed the assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='companies.company')),
                ('previous_role', models.ForeignKey(blank=True, help_text='The role held before this assignment (null on first assignment).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='roles.role')),
                ('role', models.ForeignKey(help_text='The role assigned to the user.', on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='roles.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'role_assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
